// <auto-generated />
namespace MobileShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class orderupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202206101554435_order-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
