// <auto-generated />
namespace MobileShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Category_Relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Category_Relation));
        
        string IMigrationMetadata.Id
        {
            get { return "202206071909002_Category_Relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
