// <auto-generated />
namespace MobileShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class OrderUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202206101459590_OrderUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
