// <auto-generated />
namespace MobileShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TwinCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TwinCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202205131247143_TwinCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
